import "../styles/globals.css";
import Head from "next/head";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Vladimir Băețel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favicon.png" />
        <script
          src="https://kit.fontawesome.com/e03a9c76a7.js"
          crossorigin="anonymous"
        ></script>
      </Head>
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;
